{{- if .Values.hive.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 172.80.120.3/library/nginx:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
            livenessProbe:
              httpGet:
                port: http
                path: /
              initialDelaySeconds: 5
              periodSeconds: 5
          volumeMounts:
            - name: hive-config
              mountPath: /tmp/hive-config
      volumes:
        - name: hive-config
          configMap:
            name: {{ include "hadoop.hive" . }}
{{- end -}}