{{- if .Values.hive.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-nginx
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32143
  type: NodePort
  selector:
    name: nginx
{{- end -}}