{{- if .Values.hive.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 172.80.120.3/library/nginx:latest
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "source /tmp/hadoop-config/bootstrap.sh"]
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
            livenessProbe:
              httpGet:
                port: 80
                path: /
              initialDelaySeconds: 5
              periodSeconds: 5
          volumeMounts:
            - name: hadoop-config
              mountPath: /tmp/hadoop-config
      volumes:
        - name: hadoop-config
          configMap:
            name: {{ include "hadoop.fullname" . }}
{{- end -}}