{{- if .Values.hive.enabled -}}
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: 172.80.120.3/library/nginx/nginx:1.16.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              port: http
              path: /index.html
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: http
              path: /index.html
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: hive-config
              mountPath: /tmp/hive-config
      volumes:
        - name: hive-config
          configMap:
            name: {{ include "hadoop.hive" . }}
{{- end -}}