{{- if .Values.hive.enabled -}}
apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: 172.80.120.3/library/nginx/nginx:1.16.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
{{- end -}}