{{- if .Values.hive.enabled -}}
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: 172.80.120.3/library/nginx/nginx:1.16.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          command: ['sh', '-c', 'echo Heqqqqqqqqqqqqqqqqqq']
          volumeMounts:
            - name: hive-config
              mountPath: /tmp/hive-config
          restartPolicy: Never
      volumes:
        - name: hive-config
          configMap:
            name: {{ include "hadoop.hive" . }}
{{- end -}}