{{- if .Values.hive.enabled -}}
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: 172.80.120.3/library/nginx/nginx:1.16.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
#          command: ['sh', '-c', 'echo Heqqqqqqqqqqqqqqqqqq']
#          readinessProbe:
#            httpGet:
#              path: /index.html
#              port: 80
#            initialDelaySeconds: 5
#            timeoutSeconds: 2
#          livenessProbe:
#            httpGet:
#              path: /index.html
#              port: 80
#            initialDelaySeconds: 10
#            timeoutSeconds: 2
          volumeMounts:
            - name: hive-config
              mountPath: /tmp/hive-config
      volumes:
        - name: hive-config
          configMap:
            name: {{ include "hadoop.hive" . }}
{{- end -}}